all:
  children:
    proxmox:
      hosts:
        localhost:
          ansible_host: 192.168.1.54

    vm_group:
      hosts:
        grimuar:
          ansible_host: 192.168.1.150
        admin-vm:
          ansible_host: 192.168.1.140