- name: Create grimuar VM on Proxmox
  hosts: localhost
  connection: local
  gather_facts: false # не нужно собирать факты на localhost

  vars_files:
    - ../vault/vault_proxmox.yml
    - ../group_vars/grimuar.yml
    - ../vault/vault_grim.yml

  tasks:
    - name: Create grimuar VM from cloud-init template
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        clone: cloudinit-ubuntu-template
        vmid: 9000
        newid: 106
        full: true
        force: true
        name: "{{ vm.name }}"
        cores: "{{ vm.cores }}"
        memory: "{{ vm.memory }}"
        scsihw: virtio-scsi-pci  # Обязательно для SCSI-диска!
        # Данные УЗ
        ciuser: "{{ grimuar_vm_user }}"
        cipassword: "{{ grimuar_vm_password }}"  # если понадобится
        sshkeys: "{{ grimuar_vm_ssh_public_key }}"
        # Сетевые параметры
        net:
          net0: virtio,bridge=vmbr0
        ipconfig:
          ipconfig0: ip={{ vm.ip }}/24,gw={{ vm.gw }}
        nameservers: "{{ vm.dns }}"
        state: present
