- name: Convert prepared VM into cloud-init template
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vault/vault_proxmox.yml

  tasks:
    - name: Convert VM with vmid=9000 into template
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        vmid: 9000
        state: template
